version: '3'

services:
     redis-server:
        image: 'redis'
     node-app:      
        restart: on-failure
        build: .
        ports:
           - "4001:8082"
        volumes:
            - node_modules
            - .:/app